version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
    pre_build:
      commands:
        - echo Updating npm...
        - npm i npm@latest -g
        - echo Installing prod dependencies
        - npm install --production
    build:
      commands:
        - la
        