version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
    pre_build:
      commands:
        - echo Updating npm...
        - npm i npm@latest -g
    build:
      commands:
        - echo Installing prod dependencies
        - npm install --production
        - mkdir lambdaPackage
        - mv node_modules index.js ./lambdaPackage
        - cd lambdaPackage
        - cd ../
        - ls -lt | cat
artifacts:
  files: 
    - 'index.js'
    - 'node_modules'
  discard-paths: yes