version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
  install:
    pre_build:
      commands:
        - echo Installing prod dependencies
        - npm install --production
    build:
      commands:
        - rm -r *.md && echo Creating zip package && zip -9 -r ./OpenPay.zip index.js && ls ./