version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
    pre_build:
      commands:
        - echo Updating npm...
        - npm i npm@latest -g
    build:
      commands:
        - echo Installing prod dependencies
        - npm install --production
        - mkdir lambdaPackage
        - mv node_module index.js ./lambdaPackage
        - cd lambdaPackage
        - zip -9 -r ../lambda.zip * 
        - ls -a | cat
        